### ISSUE TITLE
Syntax error in 'relatedOntologies/unece.ttl'

### ISSUE THREAD

**Issue by wouterbeek** [Federated-BDI/FEDeRATED-Semantic-Model#18]
The file `relatedOntologies/unece.ttl` contains a syntax error on line 37.730 (see screenshot).

![Screenshot from 2022-08-26 10-12-54](https://user-images.githubusercontent.com/1685012/186855820-c9f33425-b390-46c2-aac3-a9f84443b777.png)

PS: I use TriplyDB to automate syntactic and semantic checks for RDF data.  You can give TriplyDB a spin for free over at <https://triplydb.com>

**Comment by silenroc1** [comment]
Thanks for notiyfing! Triply is great ;)
